repositoryID: 5bc57007-3582-4361-8748-c7cdebfcf4ac
name: helmchart
displayName: Akonverma Helm Charts - Clouddrove
description: A collection of Helm charts maintained by Akon Verma for Clouddrove
homeURL: https://github.com/akonverma97/helmchart
repoURL: https://akonverma97.github.io/helmchart
type: helm
publisher:
  name: Akon Verma
