name: helmchart-clouddrove
displayName: Akonverma Helm Charts - Clouddrove
description: A collection of Helm charts maintained by Akon Verma for Clouddrove
homeURL: https://github.com/akonverma97/helmchart
repoURL: https://akonverma97.github.io/helmchart-clouddrove
type: helm
publisher:
  name: Akon Verma
  email: ashish.verma@clouddrove.com
  url: https://github.com/akonverma97
