name: Publish Helm Charts to GitHub Pages

on:
  push:
    branches:
      - feat/github-action
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Helm CLI
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package Helm charts
        run: |
          mkdir -p ./helmchart/packages
          echo "Found charts:"
          ls -d ./helmchart/charts/*/
          for chart_dir in ./helmchart/charts/*/; do
            echo "Packaging chart: $chart_dir"
            helm package "$chart_dir" -d ./helmchart/packages
          done

      - name: Create Helm repo index.yaml
        run: |
          helm repo index ./helmchart/packages --url https://akonverma97.github.io/helmchart

      - name: Deploy to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./helmchart/packages
          force_orphan: true

